<a href="https://colab.research.google.com/github/thenoorfatima/PyTorch/blob/main/PyTorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


A [torch.Tensor] is a multi-dimensional matrix containing elements of a single data type.




In [ ]:
scalar = torch.tensor(8)
scalar

tensor(8)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item() #tensor got back as python int

8

In [ ]:
vector = torch.tensor([1,1])
vector

tensor([1, 1])

In [ ]:
vector.ndim #num of square braces

1

In [ ]:
vector.shape  #.size() is function, .shape is sttribute

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[1,1],[2,2]]) #in pytorch anytime we encode data into numbers its of tensor datatype
MATRIX

tensor([[1, 1],
        [2, 2]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1767, 0.3312, 0.8078, 0.1299],
        [0.2104, 0.6884, 0.6341, 0.0357],
        [0.3311, 0.6387, 0.9791, 0.5967]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Random tensor with similar shape to image tensor
rimage = torch.rand(224,224,3) #height,width,color channels
rimage.shape, rimage.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zeros = torch.zeros(3,3)
zeros+1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a= torch.arange(0,100,20)
a

tensor([ 0, 20, 40, 60, 80])

In [ ]:
b = torch.zeros_like(a)
b

tensor([0, 0, 0, 0, 0])

3 Major errors in PyTorch and DL


1.   Tensors not of right datatype
2.   not the right shape
3.   not on the right device




In [ ]:
d = torch.tensor([1,2,3],dtype=None, device = "cpu", requires_grad = False)
d

tensor([1, 2, 3])

In [ ]:
f16 = d.type(torch.float16)
print(f"The tensor is of {f16.dtype} dataype, {f16.shape} shape and is on {f16.device} device.")

The tensor is of torch.float16 dataype, torch.Size([3]) shape and is on cpu device.


In [ ]:
print(f"Matrix multiplication in NN DL torch. matmul(d,d) = {torch.matmul(d,d)}, torch.mm(d,d) and d @ d= {d @ d}")
# inner dim must match
# output matrix has dim of outer dim

Matrix multiplication in NN DL torch. matmul(d,d) = 14, torch.mm(d,d) and d @ d= 14


In [ ]:
# Using Transpose to fix the axes or dimensions of a matrix to be able to matmul
c = torch.rand(2,3)
e = c.T
c,e

(tensor([[0.8394, 0.6718, 0.5277],
         [0.2503, 0.9427, 0.1417]]),
 tensor([[0.8394, 0.2503],
         [0.6718, 0.9427],
         [0.5277, 0.1417]]))

In [ ]:
# Tensor Aggregation - min, max, sum, mean
x = torch.tensor([1.0,2.0,3.0]) # mean() needs float32
torch.min(d), d.min(), d.max(), d.sum(), x.mean(), d.type(torch.float32).mean(), torch.mean(d.type(torch.float32))

(tensor(1),
 tensor(1),
 tensor(3),
 tensor(6),
 tensor(2.),
 tensor(2.),
 tensor(2.))

In [ ]:
# Positional min and max, argmin/max -> returns index
x.argmin(), x.argmax(), x[2]

(tensor(0), tensor(2), tensor(3.))

Reshaping, Stacking, Squeezing, Unsqueezing tensors


*   Reshaping -> input tensor reshaped to defined shape
*   view -> just a temporary shape image
*   stacking -> combine multiple tensors on top of each vstack/ hstack
*   squeeze -> remove all 1 dimensions from a tensor
*   unsqueeze -> add a 1 dim to a tensor
*   permute -> returns a view of input with axes/dim rearranged/swapped




In [140]:
import torch
x= torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [141]:
# adding extra dim
xnew = x.reshape(1,9)
xnew, xnew.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [142]:
# view
z = x.view(1,9)
z, z.shape


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [143]:
# changing z changes x, coz they share same memory
z[:,0] = 5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [144]:
# stack
xstack = torch.stack([x,x,x,x], dim = 1)
xstack

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [145]:
# squeeze
xnew, xnew.shape, xnew.squeeze(), xnew.squeeze().shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]),
 torch.Size([1, 9]),
 tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]),
 torch.Size([9]))

In [146]:
# unsqueeze
xnew, xnew.shape, xnew.unsqueeze(dim = 0), xnew.unsqueeze(dim = 0).shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]),
 torch.Size([1, 9]),
 tensor([[[5, 2, 3, 4, 5, 6, 7, 8, 9]]]),
 torch.Size([1, 1, 9]))

In [147]:
#permute
img = torch.rand(224,224,3) # height, width, color channels # shares view

perm = img.permute(2,0,1)   # shifts axes 0->1, 1->2, 2->0
perm.shape                  # color channels, height, width


torch.Size([3, 224, 224])

In [148]:
# INDEXING
i = x.reshape(1,3,3)
x, x.shape, i, i.shape

(tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]),
 torch.Size([9]),
 tensor([[[5, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [149]:
i[0], i[0][0], i[0][0][0]

(tensor([[5, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([5, 2, 3]),
 tensor(5))

In [153]:
i[:,0], i[:,:,1], i[0,0,1], i[:, 1, 1], i[0,1,1], i[0,2,2], i[:,:,2]

(tensor([[5, 2, 3]]),
 tensor([[2, 5, 8]]),
 tensor(2),
 tensor([5]),
 tensor(5),
 tensor(9),
 tensor([[3, 6, 9]]))

PyTorch Tensors and NumPy



*   Numpy to torch tensor -> torch.from_numpy(a)
*   Tensor to numpy       -> torch.Tensor.numpy()



In [162]:
import torch  # with this method default dtype of array and tensor (due to numpy) = float64 otherwise tensor = float32
import numpy as np

a = np.arange(1.0,8.0)
tensor = torch.from_numpy(a)  # numpy to torch
a, tensor, a+1 # change to numpy doesnt change tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([2., 3., 4., 5., 6., 7., 8.]))

In [163]:
t = torch.arange(0,10)
n = t.numpy()
n, t, n.dtype, t.dtype

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 dtype('int64'),
 torch.int64)

Reproducibility -> Reduce the randomness in NN and PyTorch using Random Seed. It flavours the randomness.

> NN: start with random nos -> tensor operations -> update random nos



In [3]:
import torch
RSEED = 12
torch.manual_seed(RSEED)
C = torch.rand(3,4)

torch.manual_seed(RSEED)
D = torch.rand(3,4)
C,D, C==D

(tensor([[0.4657, 0.2328, 0.4527, 0.5871],
         [0.4086, 0.1272, 0.6373, 0.2421],
         [0.7312, 0.7224, 0.1992, 0.6948]]),
 tensor([[0.4657, 0.2328, 0.4527, 0.5871],
         [0.4086, 0.1272, 0.6373, 0.2421],
         [0.7312, 0.7224, 0.1992, 0.6948]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [4]:
torch.cuda.is_available() # device agnostic code. This means code that'll run on CPU (always available) or GPU (if available).

False

In [6]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [7]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [8]:
# Count number of devices
torch.cuda.device_count()

0

In [9]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [10]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [11]:
tensor_on_gpu


tensor([1, 2, 3])